Repository Yammayap/widgets.workplacefutures.com, pull requests merged in 2024-02, with the labels that each got.

#9 Space Calculator Inputs Schema
  app/Enums/Widgets/SpaceCalculator/Collaboration.php
  app/Enums/Widgets/SpaceCalculator/HybridWorking.php
  app/Enums/Widgets/SpaceCalculator/Mobility.php
  app/Enums/Widgets/SpaceCalculator/Workstyle.php
  app/Models/Enquiry.php
  app/Models/SpaceCalculatorInput.php
  database/factories/SpaceCalculatorInputFactory.php
  database/migrations/2024_01_31_154133_create_space_calculator_inputs_table.php
Labels: 📦 feature

#10 Skeleton Layout Implementation
  app/Http/Controllers/Web/SpaceCalculator/LandingController.php
  app/View/Components/Footer.php
  app/View/Components/Header.php
  resources/views/components/footer.blade.php
  resources/views/components/header.blade.php
  resources/views/skeleton.blade.php
  resources/views/web/space-calculator/landing.blade.php
  routes/web.php
Labels: 📦 feature

#11 Home URL Redirect
  app/Http/Controllers/Web/HomeController.php
  routes/web.php
Labels: 📦 feature

#12 Space Calculator Landing Page
  resources/views/web/space-calculator/landing.blade.php
  tests/Feature/Http/Web/SpaceCalculator/LandingController/GetIndexTest.php
Labels: 📦 feature

#13 Space Calculator Inputs: HTTP Flow
  app/Enums/Tenant.php
  app/Enums/Traits/ProvidesSelectOptions.php
  app/Enums/Widgets/SpaceCalculator/Collaboration.php
  app/Enums/Widgets/SpaceCalculator/HybridWorking.php
  app/Enums/Widgets/SpaceCalculator/Mobility.php
  app/Enums/Widgets/SpaceCalculator/Workstyle.php
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Http/Requests/Web/SpaceCalculator/PostIndexRequest.php
  app/View/Components/Errors.php
  app/View/Components/Forms/Label.php
  app/View/Components/Forms/Select.php
  app/View/Components/Forms/Text.php
  resources/views/components/errors.blade.php
  resources/views/components/forms/label.blade.php
  resources/views/components/forms/text.blade.php
  resources/views/components/header.blade.php
  resources/views/components/select.blade.php
  resources/views/web/space-calculator/inputs.blade.php
  resources/views/web/space-calculator/landing.blade.php
  routes/web.php
  tests/Feature/Http/Web/SpaceCalculator/InputsController/GetIndexTest.php
Labels: 📦 feature

#14 Space Calculator Structure
  app/Models/SpaceCalculatorInput.php
  app/Services/SpaceCalculator/Calculator.php
  app/Services/SpaceCalculator/Config.php
  app/Services/SpaceCalculator/Inputs.php
  app/Services/SpaceCalculator/Output.php
  app/Services/SpaceCalculator/ServiceProvider.php
  config/app.php
  tests/Unit/Models/SpaceCalculatorInputTest.php
  tests/Unit/Services/SpaceCalculator/CalculatorTest.php
Labels: 📦 feature

#16 Asset Enums
  app/Enums/Widgets/SpaceCalculator/AreaType.php
  app/Enums/Widgets/SpaceCalculator/Asset.php
  app/Enums/Widgets/SpaceCalculator/CapacityType.php
Labels: 📦 feature

#15 Space Calculator Inputs: Capture data
  app/Actions/Enquiries/CreateAction.php
  app/Actions/SpaceCalculatorInputs/CreateAction.php
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Models/Enquiry.php
  app/Models/SpaceCalculatorInput.php
  app/View/Components/Forms/Select.php
  resources/views/components/forms/select.blade.php
  tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
  tests/TestCase.php
  tests/Unit/Actions/Enquiries/CreateActionTest.php
  tests/Unit/Actions/SpaceCalculatorInputs/CreateActionTest.php
Labels: 📦 feature

#17 Raw space standards added to the config
  config/widgets/space-calculator.php
Labels: 💾 system

#18 Workstyle Parameters Config
  config/widgets/space-calculator.php
Labels: 💾 system

#19 Circulation allowance config
  config/widgets/space-calculator.php
Labels: 💾 system

#20 Space Calculator Output Structure
  app/Services/SpaceCalculator/Calculator.php
  app/Services/SpaceCalculator/Config.php
  app/Services/SpaceCalculator/Inputs.php
  app/Services/SpaceCalculator/Output.php
  app/Services/SpaceCalculator/OutputAreaSize.php
  app/Services/SpaceCalculator/OutputAreaType.php
  app/Services/SpaceCalculator/OutputAsset.php
  app/Services/SpaceCalculator/OutputCapacityType.php
Labels: 📦 feature

#21 Magic Links Schema
  app/Models/MagicLink.php
  app/Models/User.php
  database/factories/MagicLinkFactory.php
  database/migrations/2024_02_08_153045_create_magic_links_table.php
Labels: 📦 feature

#22 Web Summary Output
  app/Actions/SpaceCalculatorInputs/CreateAction.php
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Http/Kernel.php
  app/Http/Middleware/GuardSpaceCalculatorOutput.php
  app/Services/SpaceCalculator/Calculator.php
  app/View/Components/SpaceCalculator/Outputs/AreaSize.php
  app/View/Components/SpaceCalculator/Outputs/AreaTypes.php
  app/View/Components/SpaceCalculator/Outputs/Assets.php
  app/View/Components/SpaceCalculator/Outputs/CapacityTypes.php
  app/View/Components/SpaceCalculator/Outputs/Questions.php
  config/widgets/space-calculator.php
  resources/views/components/space-calculator/outputs/area-size.blade.php
  resources/views/components/space-calculator/outputs/area-types.blade.php
  resources/views/components/space-calculator/outputs/assets.blade.php
  resources/views/components/space-calculator/outputs/capacity-types.blade.php
  resources/views/components/space-calculator/outputs/questions.blade.php
  resources/views/web/space-calculator/outputs.blade.php
  routes/web.php
  tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
  tests/Unit/Actions/SpaceCalculatorInputs/CreateActionTest.php
Labels: 📦 feature

#23 Asset parameters config
  config/widgets/space-calculator.php
Labels: 📦 feature

#25 SC Config Transforming
  app/Services/SpaceCalculator/Config.php
  app/Services/SpaceCalculator/ServiceProvider.php
Labels: 📦 feature

#24 Magic Link Email
  app/Actions/MagicLinks/SendAction.php
  app/Http/Controllers/Web/AuthController.php
  app/Models/MagicLink.php
  app/Models/User.php
  app/Notifications/MagicLinkNotification.php
  app/Support/Helpers.php
  config/widgets.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
  tests/Unit/Actions/MagicLinks/SendActionTest.php
  tests/Unit/Support/HelpersTest.php
Labels: 📦 feature

#28 Area Calculations
  app/Services/SpaceCalculator/AssetCalculation.php
  app/Services/SpaceCalculator/Calculator.php
Labels: 📦 feature

#29 Capacity Calculations
  app/Services/SpaceCalculator/Calculator.php
Labels: 📦 feature

#30 Dev/area calculations
  app/Services/SpaceCalculator/Calculator.php
  app/Services/SpaceCalculator/OutputAreaType.php
Labels: 📦 feature

#31 Asset Outputs
  app/Enums/Widgets/SpaceCalculator/WorkstationType.php
  app/Services/SpaceCalculator/Calculator.php
  app/Services/SpaceCalculator/OutputAsset.php
  resources/views/web/space-calculator/outputs.blade.php
Labels: 📦 feature

#32 Output Tests
  tests/Unit/Services/SpaceCalculator/CalculatorTest.php
Labels: 📦 feature

#33 Calculator Cleanup
  app/Services/SpaceCalculator/Calculator.php
  app/Services/SpaceCalculator/OutputAreaType.php
  app/View/Components/SpaceCalculator/Outputs/AreaSize.php
  app/View/Components/SpaceCalculator/Outputs/AreaTypes.php
  app/View/Components/SpaceCalculator/Outputs/Assets.php
  app/View/Components/SpaceCalculator/Outputs/CapacityTypes.php
  app/View/Components/SpaceCalculator/Outputs/Questions.php
  database/factories/SpaceCalculatorInputFactory.php
Labels: 📦 feature

#36 Capture Full Details
  app/Actions/Enquiries/AddContactDetailsAction.php
  app/Actions/Users/UpdateProfileAction.php
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Http/Requests/Web/SpaceCalculator/Summary/PostProfileRequest.php
  app/Jobs/Enquiries/TransmitToHubSpotJob.php
  app/View/Components/Forms/Checkbox.php
  app/View/Components/Forms/Textarea.php
  resources/views/components/forms/checkbox.blade.php
  resources/views/components/forms/textarea.blade.php
  resources/views/web/space-calculator/outputs.blade.php
  routes/web.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostProfileTest.php
  tests/Unit/Actions/Enquiries/AddContactDetailsActionTest.php
  tests/Unit/Actions/Users/UpdateProfileActionTest.php
Labels: 📦 feature

#37 Magic Link Endpoint
  app/Actions/MagicLinks/MarkAsAuthenticated.php
  app/Actions/MagicLinks/SendAction.php
  app/Http/Controllers/Web/AuthController.php
  app/Http/Controllers/Web/PortalController.php
  app/Http/Kernel.php
  app/Http/Middleware/VerifyMagicLink.php
  app/Models/MagicLink.php
  app/Notifications/MagicLinkNotification.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
  tests/Unit/Actions/MagicLinks/MarkAsAuthenticatedTest.php
Labels: 📦 feature

#38 Detailed Output
  app/Http/Controllers/Web/AuthController.php
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Http/Kernel.php
  app/Http/Middleware/GuardSpaceCalculatorDetailedOutput.php
  app/Http/Middleware/GuardSpaceCalculatorOutput.php
  app/Notifications/DetailedNotification.php
  resources/views/web/space-calculator/detailed-results.blade.php
  routes/web.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetDetailedTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostDetailedTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostIndexTest.php
Labels: 📦 feature

#39 Logout of Authenticated Users
  app/Http/Controllers/Web/AuthController.php
  app/Http/Controllers/WebController.php
  app/Models/User.php
  database/factories/UserFactory.php
  database/migrations/2024_02_22_162122_add_remember_token_to_users.php
  resources/views/components/header.blade.php
  resources/views/web/auth/sign-out.blade.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetSignOutTest.php
  tests/Feature/Http/Web/AuthController/PostSignOutTest.php
Labels: 📦 feature

#40 Generic magic link request form
  app/Http/Controllers/Web/AuthController.php
  app/Http/Requests/Web/Auth/PostSignInRequest.php
  resources/views/web/auth/sign-in.blade.php
  resources/views/web/auth/sign-out.blade.php
  resources/views/web/space-calculator/landing.blade.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetSignInTest.php
  tests/Feature/Http/Web/AuthController/PostSignInTest.php
Labels: 📦 feature

#42 Misc enhancements
  app/Http/Controllers/Web/AuthController.php
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Http/Controllers/Web/SpaceCalculator/LandingController.php
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Models/MagicLink.php
  app/Models/User.php
  app/Notifications/DetailedNotification.php
  app/Notifications/MagicLinkNotification.php
  app/Notifications/SummaryNotification.php
  composer.json
  composer.lock
  resources/views/components/footer.blade.php
  resources/views/components/header.blade.php
  resources/views/components/space-calculator/outputs/area-size.blade.php
  resources/views/components/space-calculator/outputs/area-types.blade.php
  resources/views/components/space-calculator/outputs/assets.blade.php
  resources/views/components/space-calculator/outputs/capacity-types.blade.php
  resources/views/components/space-calculator/outputs/questions.blade.php
  resources/views/web/auth/sign-in.blade.php
  resources/views/web/auth/sign-out.blade.php
  resources/views/web/space-calculator/detailed-results.blade.php
  resources/views/web/space-calculator/inputs.blade.php
  resources/views/web/space-calculator/landing.blade.php
  resources/views/web/space-calculator/outputs.blade.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetSignInTest.php
  tests/Feature/Http/Web/AuthController/GetSignOutTest.php
  tests/Feature/Http/Web/AuthController/PostSignOutTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
Labels: 🧽 housekeeping

#43 Dependency updates
  composer.lock
  package-lock.json
Labels: 🧽 housekeeping

#41 Error Pages UI
  resources/views/errors/401.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/405.blade.php
  resources/views/errors/419.blade.php
  resources/views/errors/429.blade.php
  resources/views/errors/4xx.blade.php
  resources/views/errors/500.blade.php
  resources/views/errors/503.blade.php
  resources/views/errors/5xx.blade.php
  resources/views/errors/layout.blade.php
Labels: 💾 system

#45 Refactoring and amends - various Trello cards
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Http/Kernel.php
  app/Http/Middleware/GuardSpaceCalculatorDetailedOutput.php
  app/Http/Middleware/GuardSpaceCalculatorSummaryOutput.php
  app/Http/Requests/Web/SpaceCalculator/Outputs/PostProfileRequest.php
  app/Http/Requests/Web/SpaceCalculator/Outputs/PostSummaryRequest.php
  app/Notifications/SpaceCalculator/DetailedNotification.php
  app/Notifications/SpaceCalculator/SummaryNotification.php
  resources/views/web/space-calculator/landing.blade.php
  resources/views/web/space-calculator/summary-results.blade.php
  routes/web.php
  tests/Feature/Http/Web/SpaceCalculator/LandingController/GetIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetDetailedTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetSummaryTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostDetailedTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostSummaryTest.php
Labels: 🧽 housekeeping

#44 Portal usage history
  app/Http/Controllers/Web/PortalController.php
  app/Http/Controllers/Web/ProfileController.php
  resources/views/web/portal/index.blade.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
  tests/Feature/Http/Web/PortalController/GetIndexTest.php
Labels: 📦 feature

#46 Force auth users to complete profile
  app/Http/Controllers/Web/ProfileController.php
  app/Http/Kernel.php
  app/Http/Middleware/EnsureAuthenticatedUserHasCompletedProfile.php
  app/Http/Requests/Web/Profile/PostIndexRequest.php
  database/factories/UserFactory.php
  resources/views/web/portal/index.blade.php
  resources/views/web/profile/index.blade.php
  routes/web.php
  tests/Feature/Http/Web/AuthController/GetSignOutTest.php
  tests/Feature/Http/Web/PortalController/GetIndexTest.php
  tests/Feature/Http/Web/ProfileController/GetIndexTest.php
  tests/Feature/Http/Web/ProfileController/PostIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetDetailedTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostDetailedTest.php
Labels: 📦 feature

#47 Summary PDF
  .github/workflows/quality-assurance.yml
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Notifications/SpaceCalculator/SummaryNotification.php
  app/PdfBuilders/PdfBuilder.php
  app/PdfBuilders/SpaceCalculator/SummaryResultsPdfBuilder.php
  composer.json
  composer.lock
  config/mail.php
  package-lock.json
  package.json
  resources/views/components/space-calculator/outputs/assets.blade.php
  resources/views/pdfs/footer.blade.php
  resources/views/pdfs/header.blade.php
  resources/views/pdfs/space-calculator/summary.blade.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostSummaryTest.php
  tests/Unit/Notifications/SpaceCalculator/SummaryNotificationTest.php
  tests/Unit/PdfBuilders/SpaceCalculator/SummaryResultsPdfBuilderTest.php
Labels: 📦 feature

#49 Detailed output pdf
  app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
  app/Notifications/SpaceCalculator/DetailedNotification.php
  app/PdfBuilders/SpaceCalculator/DetailedResultsPdfBuilder.php
  resources/views/pdfs/space-calculator/detailed.blade.php
  tests/Unit/Notifications/SpaceCalculator/DetailedNotificationTest.php
  tests/Unit/PdfBuilders/SpaceCalculator/DetailedResultsPdfBuilderTest.php
Labels: 📦 feature

#48 Auth user logic flaw
  app/Actions/Enquiries/CreateAction.php
  app/Http/Controllers/Web/SpaceCalculator/InputsController.php
  app/Http/Middleware/GuardSpaceCalculatorSummaryOutput.php
  app/Http/Requests/Web/SpaceCalculator/Inputs/PostIndexRequest.php
  resources/views/web/space-calculator/detailed-results.blade.php
  resources/views/web/space-calculator/inputs.blade.php
  tests/Feature/Http/Web/SpaceCalculator/InputsController/GetIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetSummaryTest.php
  tests/Feature/Http/Web/SpaceCalculator/OutputsController/PostSummaryTest.php
  tests/Unit/Actions/Enquiries/CreateActionTest.php
Labels: 🐛 bug, 📦 feature
