Repository Yammayap/widgets.workplacefutures.com, pull requests merged in 2024-01, with the labels that each got.

#1 Sync repo to AWS CodeCommit
  .github/workflows/sync-to-codecommit.yml
Labels: 💾 system

#3 Tenant manager / identification
  app/Enums/Contracts/HasLabel.php
  app/Enums/Tenant.php
  app/Http/Kernel.php
  app/Http/Middleware/SetTenant.php
  app/Providers/RouteServiceProvider.php
  app/Services/TenantManager/ServiceProvider.php
  app/Services/TenantManager/TenantManager.php
  config/app.php
  public/img/tenants/logos/ambit.svg
  public/img/tenants/logos/modus.svg
  public/img/tenants/logos/platfform.svg
  public/img/tenants/logos/two.png
  public/img/tenants/logos/wfg.svg
  resources/views/skeleton.blade.php
  routes/web.php
  storage/debugbar/.gitignore
  tests/Unit/ExampleTest.php
  tests/Unit/Services/TenantManager/TenantManagerTest.php
Labels: 📦 feature

#4 User Schema
  app/Models/User.php
  database/factories/UserFactory.php
  database/migrations/2024_01_29_170158_create_users_table.php
Labels: 📦 feature

#6 Enquiry Schema
  app/Models/Enquiry.php
  app/Models/User.php
  database/factories/EnquiryFactory.php
  database/migrations/2024_01_30_170730_create_enquiries_table.php
Labels: 📦 feature

#7 Sentry Context Middleware
  app/Http/Kernel.php
  app/Http/Middleware/SentryContext.php
  app/Models/User.php
  app/Providers/RouteServiceProvider.php
Labels: 💾 system, 🧽 housekeeping
